# Generated by Django 3.0.8 on 2020-08-10 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MODELNAME',
            new_name='dict',
        ),
    ]
