# Generated by Django 3.0.8 on 2020-08-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapi', '0002_auto_20200810_0108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dict',
            new_name='Dict_word',
        ),
    ]
